# Portas e Ações
ports:
  - port: 4200
    onOpen: ignore
  - port: 3000
    onOpen: open-browser

# Tarefas na Inicialização
tasks:
  - command: >
      echo "Instalando create-react-app global, entrando na pasta e executando package" &&
      npm i -g create-react-app &&
      cd exercicios &&
      npm i &&
      npm run start


# Github
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
